name: TimeTable
description: TimeTable Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^0.1.3
    barcode_scan: any
    http: ^0.12.2
    path_provider: ^1.6.14

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_launcher_icons: ^0.7.5

flutter_icons:
    image_path: "icon.png" 
    android: true
    ios: true

flutter:
    uses-material-design: true