name: Backend Deploy

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Deploy to Heroku
      run: cd backend && mvn heroku:deploy -Dmaven.test.skip
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU }}
